name: Actions

on:
  pull_request:
    branches:
    - main

jobs:

  swiftlang_checks:
    name: Swiftlang Checks
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
    with:
      license_header_check_project_name: "project"
      format_check_enabled : true
      broken_symlink_check_enabled : true
      unacceptable_language_check_enabled : true
      api_breakage_check_enabled : false
      docs_check_enabled : false
      license_header_check_enabled : false
      shell_check_enabled : false
      yamllint_check_enabled : false
      python_lint_check_enabled : false

  bb_checks:
    name: BB Checks
    uses: BinaryBirds/github-workflows/.github/workflows/extra_soundness.yml@main
    with:
      local_swift_dependencies_check_enabled : true
      run_tests_with_cache_enabled : true