name: Actions

on:
  pull_request:
    branches:
    - main

jobs:

  bb_checks:
    name: BB Checks
    uses: BinaryBirds/github-workflows/.github/workflows/extra_soundness.yml@main
    with:
      local_swift_dependencies_check_enabled : true

  swiftlang_checks:
    name: Swiftlang Checks
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
    with:
      license_header_check_project_name: "project"
      format_check_enabled : true
      broken_symlink_check_enabled : true
      unacceptable_language_check_enabled : true
      api_breakage_check_enabled : false
      docs_check_enabled : false
      license_header_check_enabled : false
      shell_check_enabled : false
      yamllint_check_enabled : false
      python_lint_check_enabled : false

  run-tests:
    name: Run Tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-15]
        include:
          - os: ubuntu-latest
            image:
            - 'swift:6.0'
          - os: macos-15
            image: ''
    runs-on: ${{ matrix.os }}

    steps:
      - name: Add keys to ssh-agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: |
            ${{ secrets.ADD_SECRET_HERE }}
            
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Swift Tests
        shell: bash
        run: |
          if [[ "$OSTYPE" == "linux-gnu"* ]]; then  # if OS is linux
              git config --global --add safe.directory $PWD
          fi
          swift test --parallel