#!/usr/bin/env bash
set -euo pipefail

log() { printf -- "** %s\n" "$*" >&2; }
error() { printf -- "** ERROR: %s\n" "$*" >&2; }
fatal() { error "$@"; exit 1; }

REPO_ROOT="$(git -C "$PWD" rev-parse --show-toplevel)"

log "111"

# Attempt to capture the output of git shortlog
contributors=$(git shortlog -es 2>/dev/null)

# Check if the command succeeded and if the result is empty
if [ $? -ne 0 ]; then
    fatal "Error: Unable to run 'git shortlog'. Are you in a valid git repository?"
fi

# Check if the output is empty
if [ -z "$contributors" ]; then
    echo "No contributors found."
else
    # Process and format the output
    contributors=$(echo "$contributors" | awk '{$1=""; print "- " $0}')
    echo "Contributors list:"
    echo "$contributors"
fi

log "Creating file..."

cat > "$REPO_ROOT/CONTRIBUTORS.txt" <<- EOF
	### Contributors
	$contributors
	
	**Updating this list**
	Please do not edit this file manually. It is generated using \`generate-contributors-list.sh\`. 
	If a name is misspelled or appearing multiple times: add an entry in \`./.mailmap\`.
EOF

log "✅ CONTRIBUTORS.txt created with no errors."