#!/usr/bin/env bash
set -euo pipefail

log() { printf -- "** %s\n" "$*" >&2; }

log "111"

REPO_ROOT="$(git -C "$PWD" rev-parse --show-toplevel)"

log "$REPO_ROOT"

log "222"
#contributors=$(git shortlog -es | cut -f2 | sed 's/^/- /')
contributors=$(git shortlog -es | awk '{$1=""; print "- " $0}')

log "333"

log "Creating file..."

cat > "$REPO_ROOT/CONTRIBUTORS.txt" <<- EOF
	### Contributors

	$contributors

	**Updating this list**

	Please do not edit this file manually. It is generated using \`generate-contributors-list.sh\`. 
	If a name is misspelled or appearing multiple times: add an entry in \`./.mailmap\`.
EOF

log "✅ CONTRIBUTORS.txt created with no errors."