#!/usr/bin/env bash
set -euo pipefail

log() { printf -- "** %s\n" "$*" >&2; }

REPO_ROOT="$(git -C "$PWD" rev-parse --show-toplevel)"

log "111"

contributors=$(git shortlog -es)

log "222"

if [ -z "$contributors" ]; then
    log "No contributors found."
	exit 0
else
    contributors=$(echo "$contributors" | awk '{$1=""; print "- " $0}')
    log "Contributors list:"
fi

log "Creating file..."

cat > "$REPO_ROOT/CONTRIBUTORS.txt" <<- EOF
	### Contributors
	$contributors
	
	**Updating this list**
	Please do not edit this file manually. It is generated using \`generate-contributors-list.sh\`. 
	If a name is misspelled or appearing multiple times: add an entry in \`./.mailmap\`.
EOF

log "✅ CONTRIBUTORS.txt created with no errors."